### ISSUE TITLE
Support for other retro hardware

### ISSUE THREAD

**Issue by jan-kleks** [kbeckmann/PicoCart64#43]
Hello and thank you for this awesome project!

Have you got any plans to support other retro hardware? Having cheap flashcarts could definitely help the retro homebrew scene. Check out some of the awesome stuff that people are making: https://old.reddit.com/r/retrogamedev/

**Comment by kbeckmann** [comment]
Not at the moment. This project takes up a lot of my time currently. Lots of work left to do.
