### ISSUE TITLE
can't run testrom

### ISSUE THREAD

**Issue by hpx1984** [kbeckmann/PicoCart64#47]
Hi Sir

built one lite ,can boot to the menu but can't run testROM(there has one fail item)
![image](https://user-images.githubusercontent.com/76941051/236666961-7c5f3570-abfb-4aff-9cbd-15d8ea406c62.png)
pressed all button and no action 
![image](https://user-images.githubusercontent.com/76941051/236666981-d3c085f9-e6ac-4f36-9bec-dc6ea3cfb7e3.png)

My step as below, please help me for improve it, many thanks Sir
1. programmed picocart64-v1-ntsc.uf2
2. Created testrom.uf2
3. programmed testrom.uf2

**Comment by kbeckmann** [comment]
You have successfully booted the test rom actually. The failed test is a persistent SRAM test - if you press the reset button it will pass. 

The menu is just a mock menu. It doesn’t do anything.

**Comment by hpx1984** [comment]
many thanks your quickly replied ,Sir

is it meets this lite version still can't run any ROMs or just can run the ROMs which show in the mock menu ?

i want to buy a Weact Board if it can support to run the ROM

**Comment by kbeckmann** [comment]
Follow the steps in https://github.com/kbeckmann/PicoCart64/blob/develop/sw/README.md or use https://picoc.art to change the rom

**Comment by hpx1984** [comment]
thank you so much ,sir
My 16m board will arrive end of this week, so happy time on your project, so great project
