### ISSUE TITLE
[question] Could you connect more SPI devices to the QSPI boot flash bus?

### ISSUE THREAD

**Issue by JensRestemeier** [kbeckmann/PicoCart64#48]
I was wondering, if you run the code from RAM, could you connect more flash or an SD-card to the QSPI pins? You won't have the execute-in-place available, but could store data?
Or is there a hardware/software limitation?

That would free up a few pins for the N64 bus.

**Comment by dogtopus** [comment]
You actually can and it has been done before IIRC. Although bank-switching like this tends to be expensive latency-wise and console that use the flashcart are usually very picky about any sorts of latencies.

**Comment by JensRestemeier** [comment]
Thanks, I was expecting that only some kind of menu (or homebrew) would access those extra devices, and could avoid cartridge access while those devices are mapped in.
