### ISSUE TITLE
[Idea] What about using MCP23017?

### ISSUE THREAD

**Issue by JPZV** [kbeckmann/PicoCart64#49]
I was thinking, right now we have only three free gpios remaining, which could be used for Savegames or for SD Card, but not both at the same time/cartridge, so, what about using a [MCP23017](https://www.alldatasheet.com/datasheet-pdf/pdf/195324/MICROCHIP/MCP23017.html) (GPIO expansion module) in not-crucial timing I/O?

For example (disclaimer: I'm not yet familiar with the code), it's obvious that we couldn't use it with AD* pins, but what about Cold Reset? Or maybe for CS pins on SPI modules)

It's just an idea btw, so don't take it as a solid solution

**Comment by kbeckmann** [comment]
Thanks for the suggestion. This is not something I am investigating. I have changed focus for this project to keeping it simple and reduce external components.
