### ISSUE TITLE
Compatipel with that pico?

### ISSUE THREAD

**Issue by Liriel-666** [kbeckmann/PicoCart64#51]
![20231225_002048](https://github.com/kbeckmann/PicoCart64/assets/10562572/dd2222dd-7c72-4cc7-9e1d-c9954bc5dfe4)
Is the lite version of the board compatible with that pico 2040?

**Comment by kbeckmann** [comment]
No, not without modifications. Notice the pins vin and vout, and compare with the original or weact pico board.

**Comment by Liriel-666** [comment]
is Vin and Vout the only difference?
sry i am not that big in the pico thing and for me the rest looks good

**Comment by Liriel-666** [comment]
to what i can see the pinout ist most the same to the non weact pico. 
i see some difference  in the last 10 pins but i dont now how to fix it.
What pin of the lite  1.4 board must connect to what pin on the black pico board?


![4103933618_w600_h600_4103933618](https://github.com/kbeckmann/PicoCart64/assets/10562572/47bb61fd-2c31-4f6c-a704-8109cd25c79d)
![423FEC27-201C-4091-B185-F9E24A5EBFB9](https://github.com/kbeckmann/PicoCart64/assets/10562572/70e7d109-7c97-47fa-867b-f4e0a1031c21)

**Comment by curcius** [comment]
Were you able to use this card? I bought the same one and did all the soldering points but it doesn't generate an image on the N64 =[

**Comment by curcius** [comment]
Updating, I was able to run Homebre as Testrom and a cell phone game converted to UF2, but the Nintendo 64 games don't start at all. I've checked pin by pin and there are no shorts or soldering failures.

**Comment by ppattss** [comment]
> Updating, I was able to run Homebre as Testrom and a cell phone game converted to UF2, but the Nintendo 64 games don't start at all. I've checked pin by pin and there are no shorts or soldering failures.

It might be related to region-checking and not having the correct one selected when making the UF2 file? or CIC issue?

Did you reconnect VREF to GP29? the VREF jumper isnt connected on the board i got, but is in all the pics of that board.

**Comment by curcius** [comment]
> > Updating, I was able to run Homebre as Testrom and a cell phone game converted to UF2, but the Nintendo 64 games don't start at all. I've checked pin by pin and there are no shorts or soldering failures.
> 
> It might be related to region-checking and not having the correct one selected when making the UF2 file? or CIC issue?
> 
> Did you reconnect VREF to GP29? the VREF jumper isnt connected on the board i got, but is in all the pics of that board.

Thank you for responding, but I've tried everything and neither UF2 NTSC nor PAL M works, I've tested several games and nothing, I've closed and opened the jumper and it gives the same results... I believe it's some incompatibility with the flash, no. I can think of nothing else, the rpi works, I've tested it with other programs like Micropython, but 64 games don't run, just homebrew...

**Comment by curcius** [comment]
I managed to solve it, I had to use the 3v3 from the console board directly on the RPI, I was using the RPI's USB power supply and it didn't work, I made the jumper to the 3v3 on the RPI and it worked perfect. Thank you everyone, I hope the project moves forward. 
![20240119_123903](https://github.com/kbeckmann/PicoCart64/assets/1108722/1157f251-b727-4282-8dbd-4cb20db5539f)

**Comment by Liriel-666** [comment]
i dont get my to work with a weact pico
![20240119_174603](https://github.com/kbeckmann/PicoCart64/assets/10562572/5a666310-97c2-46ec-9ce0-50bed5226076)

I solder all correct. 
because i destroy on unsolderng the other pico i replace the jumper with a cable
all solderpoints are there and correct. 
i even solder the debug port

nothing with any uf2 convertet file.
I put firmware on it and then restart it. 
then i put the testrom or a game on it and nothing on my pal n64

**Comment by samowitsch** [comment]
@Liriel-666 i have the exact same problem as you. I ordered like you a WeAct RP 2040 and nothing is working. Did you solved it in the meantime?
GPIO 26 and 27 are shiftet one pin could that be? There is no "RUN" pin on the WeAct compared to the original Pico board?
[comparison-with-PicoCart64-schematic.pdf](https://github.com/user-attachments/files/16240468/comparison-with-PicoCart64-schematic.pdf)

**Update:** debug port has no connection on pcb. GPIO 26/27 doesn't matter if i am right. I don't know why the WeAct  2040 16MB is not working?!

**Comment by samowitsch** [comment]
@kbeckmann Neither the WeAct 16MB nor the Bitfunx 16MB Pico board works. Are there any secret tips that aren't mentioned anywhere? Does the picocart64-v1-pal/ntsc.uf2 work with any Flash Ram size?

**Comment by kbeckmann** [comment]
> @kbeckmann Neither the WeAct 16MB nor the Bitfunx 16MB Pico board works. Are there any secret tips that aren't mentioned anywhere? Does the picocart64-v1-pal/ntsc.uf2 work with any Flash Ram size?

I'm sorry, I don't know to be honest. WeAct 16MB have been known to work earlier, but it's also possible that the manufacturer changed something, e.g. maybe the flash is not the 133MHz variant or so?

Edit: This was meant as a reply to @samowitsch

**Comment by samowitsch** [comment]
The following "solutions" work for me. (By the way, thanks for the feedback on Discord from be0w0lf710, which pointed me in the right direction. I would never have questioned BSS84 that something is not working properly here.)

**Bitfunx board (100% pin compatible)**
![pico-bitfunx-board-jumper-to-vbus](https://github.com/user-attachments/assets/648527d0-6f89-4cb9-9050-e08420cec2cb)

**Weact board**
![pico-weact-board-jumper-to-vsys](https://github.com/user-attachments/assets/ce398052-baec-4fa4-ac43-51c50c6bb4a2)

**Comment by kbeckmann** [comment]
I just want to put a warning text here and say that you need to be careful and know what you’re doing if you are connecting it like this. You risk connecting your 5V USB supply voltage to the N64 3.3V rail which could cause damage.

**Comment by reflekt00** [comment]
@samowitsch has this setup bridging 5V on the weact board to the 3.3V rail been working reliably for you? I'm in the same boat, the cart won't load a rom with the transistor in place.

**Comment by samowitsch** [comment]
@reflekt00 it worked for me without the components and just a jumper wire. But with this „workaround“ the USB cable should not be connected when the picocart is plugged into the N64.
