### ISSUE TITLE
Stackypi support

### ISSUE THREAD

**Issue by Tom-Neverwinter** [kbeckmann/PicoCart64#55]
I was randomly looking at rpi2040 boards and noticed this newish one

64MB vs the 16MB 

I'm assuming if the pinout is the same it could be flashed with a larger u2f file and work the same? 

https://www.kickstarter.com/projects/ash-kumar/pico-zero-rp2040-pico-based-board-on-pi-zero-form-factor

**Comment by kbeckmann** [comment]
The root issue is access time to read from the flash, it has to be very fast. The flash controller in the rp2040 has a limit on 16MB. Not sure how this Kickstarter project is doing to solve the issue. 

This fork explores a way around this limitation https://github.com/pdaxrom/N64cart

**Comment by jshield** [comment]
@Tom-Neverwinter it is not meant to be brother, despite what it says. the Stacky Pi ships with 64Mbit of memory which is 8MiB

**Comment by kbeckmann** [comment]
Ah yeah it’s unfortunate that this mistake happens over and over again, bit vs byte. Let’s hope that the next RP chip solves this issue.  

To clarify; I’m referring to the 16 MByte limit.

**Comment by Tom-Neverwinter** [comment]
the naming convention used by the pico is annoying and confusing. we stopped using bites over a decade ago

**Comment by kbeckmann** [comment]
The flash chip vendors usually use bits in their product descriptions and model names like this one https://www.winbond.com/hq/product/code-storage-flash-memory/serial-nor-flash/?__locale=en&partNo=W25Q128JV
