### ISSUE TITLE
new pi pico boards: SparkFun Pro Micro RP2350

### ISSUE THREAD

**Issue by Tom-Neverwinter** [kbeckmann/PicoCart64#60]
https://www.youtube.com/watch?v=UnIa2jbEHRk
SparkFun Pro Micro RP2350

The RP3250 is a unique dual-core microcontroller with two ARM® Cortex® M33 processors and two Hazard3 RISC-V processors, all running at up to 150 MHz! Now, this doesn't mean the RP2350 is a quad-core microcontroller. Instead, users can select which two processors to run on boot instead. You can run two processors of the same type or one of each. The RP2350 also features 520kB SRAM in ten banks, a host of peripherals including two UARTs, two SPI and two I2C controllers, and a USB 1.1 controller for host and device support.

The Pro Micro also includes two expanded memory options: 16MB of external Flash and 8MB PSRAM connected to the RP2350's QSPI controller. The RP2350 Pro Micro works with C/C++ using the Pico SDK and MicroPython development environments.

**Comment by kbeckmann** [comment]
RP2350/RP2354 sure is an interesting chip! Will keep an eye on it.

It doesn't seem to solve the 16MByte limit (it does support having two separate 16 MB QSPI chips though, but 64MByte seems to not be supported out of the box).
