### ISSUE TITLE
Prepare firmware for the ESP32-C3

### ISSUE THREAD

**Issue by kbeckmann** [kbeckmann/PicoCart64#7]
Prepare some kind of firmware for the ESP32-C3 so it can be used as a WiFi peripheral.

Most promising path seems to be to run https://github.com/adafruit/nina-fw on the ESP32-C3, and https://github.com/adafruit/WiFiNINA on the RP2040.

Ensure that it can be programmed by #4

**Comment by kbeckmann** [comment]
See https://github.com/espressif/esp32c3-direct-boot-example for a simple project setup

**Comment by kbeckmann** [comment]
Might fork https://github.com/espressif/esp-at and configure it to our needs?

**Comment by kbeckmann** [comment]
Or maybe https://github.com/arduino/nina-fw

**Comment by kbeckmann** [comment]
https://github.com/adafruit/nina-fw

**Comment by kbeckmann** [comment]
https://github.com/adafruit/WiFiNINA/

**Comment by zzzbatmand** [comment]
Any progress with nina-fw on the ESP32-C3?
